name: znmine
main: ru.znmine.Main
author: Skepter&znsoft
version: 1.0
description: znmine menu plugin 
commands:
    mymenu:
        description: Add or remove commands icon in player menu.
        usage: /mymenu add command params
    менюшка:
        description: Добавление или удаление иконок меню
        usage: /менюшка добавить команда с параметрами        
    меню:
        description: Добавление или удаление иконок меню
        usage: /меню добавить команда с параметрами                